import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { WorkoutActivityType, WorkoutTypeIdentifier, isHealthDataAvailable, requestAuthorization, queryWorkoutSamples, queryStatisticsForQuantity, type WorkoutProxyTyped } from '@kingstinct/react-native-healthkit';

const HEALTHKIT_PERMISSIONS_KEY = '@alchemize_healthkit_permissions';
const HEALTHKIT_LAST_SYNC_KEY = '@alchemize_healthkit_last_sync';
const ACTIVE_ENERGY_IDENTIFIER = 'HKQuantityTypeIdentifierActiveEnergyBurned' as const;
const EXERCISE_TIME_IDENTIFIER = 'HKQuantityTypeIdentifierAppleExerciseTime' as const;
const STEP_COUNT_IDENTIFIER = 'HKQuantityTypeIdentifierStepCount' as const;

export type HealthKitPermissionStatus = 'notDetermined' | 'authorized' | 'denied' | 'unavailable';
export interface HealthKitPermissions { activeEnergy: HealthKitPermissionStatus; workouts: HealthKitPermissionStatus; exerciseMinutes: HealthKitPermissionStatus; overallStatus: HealthKitPermissionStatus; lastUpdated: string | null; }
export interface HealthKitWorkout { id: string; workoutType: string; startDate: string; endDate: string; duration: number; caloriesBurned: number | null; source: 'apple_health' | 'manual' | 'estimated'; sourceName: string; isEstimated: boolean; }
export interface HealthKitActivityData { date: string; activeEnergyBurned: number | null; exerciseMinutes: number | null; steps: number | null; workouts: HealthKitWorkout[]; failedMetrics: string[]; }
const DEFAULT_PERMISSIONS: HealthKitPermissions = { activeEnergy: 'notDetermined', workouts: 'notDetermined', exerciseMinutes: 'notDetermined', overallStatus: 'notDetermined', lastUpdated: null };
const LABELS: Partial<Record<keyof typeof WorkoutActivityType, string>> = { traditionalStrengthTraining: 'Strength Training', functionalStrengthTraining: 'Functional Training', highIntensityIntervalTraining: 'HIIT', crossTraining: 'Cross Training', danceInspiredTraining: 'Dance', mixedMetabolicCardioTraining: 'Mixed Cardio' };
function formatActivity(type: WorkoutActivityType) { const key = WorkoutActivityType[type] as keyof typeof WorkoutActivityType | undefined; if (!key) return 'Workout'; if (LABELS[key]) return LABELS[key]!; const s = key.replace(/([a-z])([A-Z])/g, '$1 $2'); return s.charAt(0).toUpperCase() + s.slice(1); }
function mapWorkout(w: WorkoutProxyTyped): HealthKitWorkout { const start = w.startDate; const end = w.endDate; const duration = Math.max(0, Math.min(1440, Math.round(Number(w.duration?.quantity) || 0))); const calories = w.totalEnergyBurned ? Math.max(0, Math.min(20000, Math.round(Number(w.totalEnergyBurned.quantity) || 0))) : null; return { id: w.uuid, workoutType: formatActivity(w.workoutActivityType), startDate: start.toISOString(), endDate: end.toISOString(), duration, caloriesBurned: calories, source: 'apple_health', sourceName: w.sourceRevision?.source?.name ?? 'Apple Health', isEstimated: false }; }
function localDateKey(date: Date) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`; }
function dayBounds(date: Date) { const start = new Date(date); start.setHours(0, 0, 0, 0); const end = new Date(start); end.setDate(end.getDate() + 1); return { start, end }; }
export function getLocalDateKey(date = new Date()) { return localDateKey(date); }
export function isHealthKitAvailable() { return Platform.OS === 'ios' && isHealthDataAvailable(); }
export function isHealthKitSupported() { if (Platform.OS === 'web') return { supported: false, reason: 'HealthKit is not available on web. Use the mobile app to sync wearable data.' }; if (Platform.OS === 'android') return { supported: false, reason: 'Apple Health is only available on iOS devices.' }; if (!isHealthDataAvailable()) return { supported: false, reason: 'Health data is not available on this device.' }; return { supported: true, reason: 'HealthKit is available on this device.' }; }
export async function getStoredPermissions() { try { const stored = await AsyncStorage.getItem(HEALTHKIT_PERMISSIONS_KEY); if (stored) return JSON.parse(stored) as HealthKitPermissions; } catch (error) { console.error('[HealthKit] Error loading permissions', error); } return DEFAULT_PERMISSIONS; }
export async function savePermissions(permissions: HealthKitPermissions) { try { await AsyncStorage.setItem(HEALTHKIT_PERMISSIONS_KEY, JSON.stringify(permissions)); } catch (error) { console.error('[HealthKit] Error saving permissions', error); } }
export async function requestHealthKitPermissions() { const { supported } = isHealthKitSupported(); if (!supported) { const unavailable = { ...DEFAULT_PERMISSIONS, activeEnergy: 'unavailable' as const, workouts: 'unavailable' as const, exerciseMinutes: 'unavailable' as const, overallStatus: 'unavailable' as const, lastUpdated: new Date().toISOString() }; await savePermissions(unavailable); return unavailable; } const requested = [ACTIVE_ENERGY_IDENTIFIER, EXERCISE_TIME_IDENTIFIER, STEP_COUNT_IDENTIFIER, WorkoutTypeIdentifier] as const; const ok = await requestAuthorization({ toRead: requested }); const status: HealthKitPermissionStatus = ok ? 'authorized' : 'denied'; const permissions = { activeEnergy: status, workouts: status, exerciseMinutes: status, overallStatus: status, lastUpdated: new Date().toISOString() }; await savePermissions(permissions); return permissions; }
export async function checkHealthKitPermissions() { const permissions = await getStoredPermissions(); if (!isHealthKitSupported().supported && permissions.overallStatus === 'authorized') return { ...permissions, overallStatus: 'unavailable' as const, activeEnergy: 'unavailable' as const, workouts: 'unavailable' as const, exerciseMinutes: 'unavailable' as const }; return permissions; }
export async function revokeHealthKitPermissions() { await savePermissions(DEFAULT_PERMISSIONS); await AsyncStorage.removeItem(HEALTHKIT_LAST_SYNC_KEY); }
export async function getLastSyncTime() { try { return await AsyncStorage.getItem(HEALTHKIT_LAST_SYNC_KEY); } catch { return null; } }
export async function setLastSyncTime(time: string) { try { await AsyncStorage.setItem(HEALTHKIT_LAST_SYNC_KEY, time); } catch (error) { console.error('[HealthKit] Error saving last sync time', error); } }
export async function fetchHealthKitWorkouts(startDate: Date, endDate: Date): Promise<HealthKitWorkout[]> { if ((await checkHealthKitPermissions()).workouts !== 'authorized') return []; try { return (await queryWorkoutSamples({ filter: { date: { startDate, endDate } }, limit: 0, ascending: false })).map(mapWorkout); } catch (error) { console.error('[HealthKit] Error fetching workouts', error); return []; } }
export async function fetchHealthKitActivity(date: Date, includeWorkouts = true): Promise<HealthKitActivityData | null> { if ((await checkHealthKitPermissions()).overallStatus !== 'authorized') return null; const { start, end } = dayBounds(date); const failedMetrics: string[] = []; const read = async (name: string, query: () => Promise<any>) => { try { const result = await query(); return Math.max(0, Math.round(Number(result?.sumQuantity?.quantity) || 0)); } catch (error) { failedMetrics.push(name); console.error(`[HealthKit] Error fetching ${name}`, error); return null; } }; const [activeEnergyBurned, exerciseMinutes, steps] = await Promise.all([read('active energy', () => queryStatisticsForQuantity(ACTIVE_ENERGY_IDENTIFIER, ['cumulativeSum'], { filter: { date: { startDate: start, endDate: end } } })), read('exercise minutes', () => queryStatisticsForQuantity(EXERCISE_TIME_IDENTIFIER, ['cumulativeSum'], { filter: { date: { startDate: start, endDate: end } } })), read('steps', () => queryStatisticsForQuantity(STEP_COUNT_IDENTIFIER, ['cumulativeSum'], { filter: { date: { startDate: start, endDate: end } } }))]); const workouts = includeWorkouts ? await fetchHealthKitWorkouts(start, end) : []; if (failedMetrics.length === 3 && !includeWorkouts) return null; return { date: localDateKey(start), activeEnergyBurned, exerciseMinutes, steps, workouts, failedMetrics }; }
export async function syncHealthKitData(): Promise<{ success: boolean; partial: boolean; workoutsImported: number; daysUpdated: number; failedDays: string[]; message: string }> { if ((await checkHealthKitPermissions()).overallStatus !== 'authorized') return { success: false, partial: false, workoutsImported: 0, daysUpdated: 0, failedDays: [], message: 'HealthKit permissions not granted. Please enable the requested Health permissions in Settings.' }; const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - 7); start.setHours(0, 0, 0, 0); const workouts = await fetchHealthKitWorkouts(start, end); const { workoutSessionsDb, normalizedMetricsDb } = await import('./database'); let workoutsImported = 0; for (const workout of workouts) { const id = `healthkit_${workout.id}`; if (await workoutSessionsDb.getById(id)) continue; await workoutSessionsDb.create({ id, templateId: 'healthkit', startedAt: new Date(workout.startDate).getTime(), endedAt: new Date(workout.endDate).getTime(), durationMinutes: workout.duration, completed: true, caloriesEstimate: workout.caloriesBurned, source: 'wearable' }); workoutsImported++; } let daysUpdated = 0; const failedDays: string[] = []; for (let cursor = new Date(start); cursor < end; cursor.setDate(cursor.getDate() + 1)) { const activity = await fetchHealthKitActivity(cursor, false); if (!activity) { failedDays.push(localDateKey(cursor)); continue; } const existing = await normalizedMetricsDb.getByDate(activity.date); const metric = { id: existing?.id ?? `healthkit_${activity.date}`, date: activity.date, activeMinutes: activity.exerciseMinutes ?? existing?.activeMinutes ?? 0, caloriesActive: activity.activeEnergyBurned ?? existing?.caloriesActive ?? 0, steps: activity.steps ?? existing?.steps ?? 0, source: 'wearable' as const, deviceType: 'none' as const }; if (existing) await normalizedMetricsDb.update(metric); else await normalizedMetricsDb.create(metric); daysUpdated++; if (activity.failedMetrics.length > 0) failedDays.push(`${activity.date} (${activity.failedMetrics.join(', ')})`); } const partial = failedDays.length > 0; if (daysUpdated > 0) await setLastSyncTime(new Date().toISOString()); return { success: daysUpdated > 0 && !partial, partial, workoutsImported, daysUpdated, failedDays, message: partial ? `Health data partially synced. Existing values were preserved where reads failed: ${failedDays.join(', ')}` : workoutsImported > 0 ? `Synced ${workoutsImported} new workout${workoutsImported === 1 ? '' : 's'} from Apple Health` : 'Apple Health activity is up to date.' }; }
export function formatWorkoutType(type: string) { const map: Record<string, string> = { HKWorkoutActivityTypeRunning: 'Running', HKWorkoutActivityTypeWalking: 'Walking', HKWorkoutActivityTypeCycling: 'Cycling', HKWorkoutActivityTypeSwimming: 'Swimming', HKWorkoutActivityTypeYoga: 'Yoga', HKWorkoutActivityTypeStrengthTraining: 'Strength Training', HKWorkoutActivityTypeHighIntensityIntervalTraining: 'HIIT', HKWorkoutActivityTypeFunctionalStrengthTraining: 'Functional Training', HKWorkoutActivityTypeCoreTraining: 'Core Training', HKWorkoutActivityTypeElliptical: 'Elliptical', HKWorkoutActivityTypeRowing: 'Rowing', HKWorkoutActivityTypeDance: 'Dance', HKWorkoutActivityTypePilates: 'Pilates' }; return map[type] || type; }
export function getPermissionStatusLabel(status: HealthKitPermissionStatus) { return status === 'authorized' ? 'Enabled' : status === 'denied' ? 'Denied' : status === 'unavailable' ? 'Unavailable' : 'Not Set'; }
export function getPermissionStatusColor(status: HealthKitPermissionStatus) { return status === 'authorized' ? '#22c55e' : status === 'denied' ? '#ef4444' : status === 'unavailable' ? '#6b7280' : '#f59e0b'; }
