import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { WorkoutActivityType, WorkoutTypeIdentifier, isHealthDataAvailable, requestAuthorization, queryWorkoutSamples, queryStatisticsForQuantity, type WorkoutProxyTyped } from '@kingstinct/react-native-healthkit';

const HEALTHKIT_PERMISSIONS_KEY = '@alchemize_healthkit_permissions';
const HEALTHKIT_LAST_SYNC_KEY = '@alchemize_healthkit_last_sync';
const ACTIVE_ENERGY_IDENTIFIER = 'HKQuantityTypeIdentifierActiveEnergyBurned' as const;
const EXERCISE_TIME_IDENTIFIER = 'HKQuantityTypeIdentifierAppleExerciseTime' as const;
const STEP_COUNT_IDENTIFIER = 'HKQuantityTypeIdentifierStepCount' as const;

export type HealthKitPermissionStatus = 'notDetermined' | 'authorized' | 'denied' | 'unavailable';
export interface HealthKitPermissions { activeEnergy: HealthKitPermissionStatus; workouts: HealthKitPermissionStatus; exerciseMinutes: HealthKitPermissionStatus; overallStatus: HealthKitPermissionStatus; lastUpdated: string | null; }
export interface HealthKitWorkout { id: string; workoutType: string; startDate: string; endDate: string; duration: number; caloriesBurned: number | null; source: 'apple_health' | 'manual' | 'estimated'; sourceName: string; isEstimated: boolean; }
export interface HealthKitActivityData { date: string; activeEnergyBurned: number; exerciseMinutes: number; steps: number; workouts: HealthKitWorkout[]; }
const DEFAULT_PERMISSIONS: HealthKitPermissions = { activeEnergy: 'notDetermined', workouts: 'notDetermined', exerciseMinutes: 'notDetermined', overallStatus: 'notDetermined', lastUpdated: null };
const WORKOUT_TYPE_LABEL_OVERRIDES: Partial<Record<keyof typeof WorkoutActivityType, string>> = { traditionalStrengthTraining:'Strength Training', functionalStrengthTraining:'Functional Training', highIntensityIntervalTraining:'HIIT', crossTraining:'Cross Training', danceInspiredTraining:'Dance', mixedMetabolicCardioTraining:'Mixed Cardio' };
function formatWorkoutActivityType(type: WorkoutActivityType): string { const key=WorkoutActivityType[type] as keyof typeof WorkoutActivityType|undefined; if(!key)return 'Workout'; if(WORKOUT_TYPE_LABEL_OVERRIDES[key])return WORKOUT_TYPE_LABEL_OVERRIDES[key]!; const spaced=key.replace(/([a-z])([A-Z])/g,'$1 $2'); return spaced.charAt(0).toUpperCase()+spaced.slice(1); }
function mapWorkout(workout: WorkoutProxyTyped): HealthKitWorkout { return { id:workout.uuid, workoutType:formatWorkoutActivityType(workout.workoutActivityType), startDate:workout.startDate.toISOString(), endDate:workout.endDate.toISOString(), duration:Math.max(0,Math.round(workout.duration.quantity)), caloriesBurned:workout.totalEnergyBurned?Math.max(0,Math.round(workout.totalEnergyBurned.quantity)):null, source:'apple_health', sourceName:workout.sourceRevision?.source?.name??'Apple Health', isEstimated:false }; }
export function isHealthKitAvailable(): boolean { return Platform.OS==='ios'&&isHealthDataAvailable(); }
export function isHealthKitSupported(): {supported:boolean;reason:string} { if(Platform.OS==='web')return{supported:false,reason:'HealthKit is not available on web. Use the mobile app to sync wearable data.'}; if(Platform.OS==='android')return{supported:false,reason:'Apple Health is only available on iOS devices.'}; if(!isHealthDataAvailable())return{supported:false,reason:'Health data is not available on this device.'}; return{supported:true,reason:'HealthKit is available on this device.'}; }
export async function getStoredPermissions(): Promise<HealthKitPermissions> { try { const stored=await AsyncStorage.getItem(HEALTHKIT_PERMISSIONS_KEY); if(stored)return JSON.parse(stored) as HealthKitPermissions; } catch(error){console.error('[HealthKit] Error loading permissions:',error);} return DEFAULT_PERMISSIONS; }
export async function savePermissions(permissions:HealthKitPermissions):Promise<void>{try{await AsyncStorage.setItem(HEALTHKIT_PERMISSIONS_KEY,JSON.stringify(permissions));}catch(error){console.error('[HealthKit] Error saving permissions:',error);}}
export async function requestHealthKitPermissions():Promise<HealthKitPermissions>{const{supported}=isHealthKitSupported();if(!supported){const p={...DEFAULT_PERMISSIONS,activeEnergy:'unavailable',workouts:'unavailable',exerciseMinutes:'unavailable',overallStatus:'unavailable',lastUpdated:new Date().toISOString()} as HealthKitPermissions;await savePermissions(p);return p;}const requested=await requestAuthorization({toRead:[ACTIVE_ENERGY_IDENTIFIER,EXERCISE_TIME_IDENTIFIER,STEP_COUNT_IDENTIFIER,WorkoutTypeIdentifier]});const status:HealthKitPermissionStatus=requested?'authorized':'denied';const p={activeEnergy:status,workouts:status,exerciseMinutes:status,overallStatus:status,lastUpdated:new Date().toISOString()};await savePermissions(p);return p;}
export async function checkHealthKitPermissions():Promise<HealthKitPermissions>{const stored=await getStoredPermissions();if(stored.overallStatus==='notDetermined')return stored;const{supported}=isHealthKitSupported();if(!supported&&stored.overallStatus==='authorized')return{...stored,overallStatus:'unavailable',activeEnergy:'unavailable',workouts:'unavailable',exerciseMinutes:'unavailable'};return stored;}
export async function revokeHealthKitPermissions():Promise<void>{await savePermissions(DEFAULT_PERMISSIONS);await AsyncStorage.removeItem(HEALTHKIT_LAST_SYNC_KEY);}
export async function getLastSyncTime():Promise<string|null>{try{return await AsyncStorage.getItem(HEALTHKIT_LAST_SYNC_KEY);}catch{return null;}}
export async function setLastSyncTime(time:string):Promise<void>{try{await AsyncStorage.setItem(HEALTHKIT_LAST_SYNC_KEY,time);}catch(error){console.error('[HealthKit] Error saving last sync time:',error);}}
export async function fetchHealthKitWorkouts(startDate:Date,endDate:Date):Promise<HealthKitWorkout[]>{const permissions=await checkHealthKitPermissions();if(permissions.workouts!=='authorized')return[];try{return(await queryWorkoutSamples({filter:{date:{startDate,endDate}},limit:0,ascending:false})).map(mapWorkout);}catch(error){console.error('[HealthKit] Error fetching workouts:',error);return[];}}
export async function fetchHealthKitActivity(date:Date):Promise<HealthKitActivityData|null>{const permissions=await checkHealthKitPermissions();if(permissions.overallStatus!=='authorized')return null;const dayStart=new Date(date);dayStart.setHours(0,0,0,0);const dayEnd=new Date(dayStart);dayEnd.setDate(dayEnd.getDate()+1);try{const[energy,exercise,steps,workouts]=await Promise.all([queryStatisticsForQuantity(ACTIVE_ENERGY_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:dayStart,endDate:dayEnd}}}),queryStatisticsForQuantity(EXERCISE_TIME_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:dayStart,endDate:dayEnd}}}),queryStatisticsForQuantity(STEP_COUNT_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:dayStart,endDate:dayEnd}}}),fetchHealthKitWorkouts(dayStart,dayEnd)]);return{date:localDateKey(dayStart),activeEnergyBurned:Math.max(0,Math.round(energy.sumQuantity?.quantity??0)),exerciseMinutes:Math.max(0,Math.round(exercise.sumQuantity?.quantity??0)),steps:Math.max(0,Math.round(steps.sumQuantity?.quantity??0)),workouts};}catch(error){console.error('[HealthKit] Error fetching activity:',error);return null;}}
function localDateKey(date:Date):string{const y=date.getFullYear();const m=String(date.getMonth()+1).padStart(2,'0');const d=String(date.getDate()).padStart(2,'0');return `${y}-${m}-${d}`;}
export async function syncHealthKitData():Promise<{success:boolean;workoutsImported:number;message:string}>{const permissions=await checkHealthKitPermissions();if(permissions.overallStatus!=='authorized')return{success:false,workoutsImported:0,message:'HealthKit permissions not granted. Please enable in settings.'};const endDate=new Date();const startDate=new Date();startDate.setDate(startDate.getDate()-7);startDate.setHours(0,0,0,0);const workouts=await fetchHealthKitWorkouts(startDate,endDate);const{workoutSessionsDb,normalizedMetricsDb}=await import('./database');let imported=0;for(const workout of workouts){const id=`healthkit_${workout.id}`;if(await workoutSessionsDb.getById(id))continue;await workoutSessionsDb.create({id,templateId:'healthkit',startedAt:new Date(workout.startDate).getTime(),endedAt:new Date(workout.endDate).getTime(),durationMinutes:workout.duration,completed:true,caloriesEstimate:workout.caloriesBurned??null,source:'wearable'});imported++;}
  // Store one authoritative HealthKit aggregate per day. This avoids adding each workout
  // to the same metric repeatedly and prevents wearable workouts from being double-counted.
  for(let cursor=new Date(startDate);cursor<=endDate;cursor.setDate(cursor.getDate()+1)){const activity=await fetchHealthKitActivity(new Date(cursor));if(!activity)continue;await normalizedMetricsDb.replaceForDate({id:`healthkit_${activity.date}`,date:activity.date,activeMinutes:activity.exerciseMinutes,caloriesActive:activity.activeEnergyBurned,steps:activity.steps,source:'wearable',deviceType:'none'});}
  await setLastSyncTime(new Date().toISOString());return{success:true,workoutsImported:imported,message:imported>0?`Synced ${imported} new workout${imported===1?'':'s'} from Apple Health`:workouts.length>0?'Already up to date — activity refreshed from Apple Health':'No workouts found — daily Apple Health activity was still refreshed'};}
export function formatWorkoutType(type:string):string{const map:Record<string,string>={'HKWorkoutActivityTypeRunning':'Running','HKWorkoutActivityTypeWalking':'Walking','HKWorkoutActivityTypeCycling':'Cycling','HKWorkoutActivityTypeSwimming':'Swimming','HKWorkoutActivityTypeYoga':'Yoga','HKWorkoutActivityTypeStrengthTraining':'Strength Training','HKWorkoutActivityTypeHighIntensityIntervalTraining':'HIIT','HKWorkoutActivityTypeFunctionalStrengthTraining':'Functional Training','HKWorkoutActivityTypeCoreTraining':'Core Training','HKWorkoutActivityTypeElliptical':'Elliptical','HKWorkoutActivityTypeRowing':'Rowing','HKWorkoutActivityTypeDance':'Dance','HKWorkoutActivityTypePilates':'Pilates'};return map[type]||type;}
export function getPermissionStatusLabel(status:HealthKitPermissionStatus):string{return status==='authorized'?'Enabled':status==='denied'?'Denied':status==='unavailable'?'Unavailable':'Not Set';}
export function getPermissionStatusColor(status:HealthKitPermissionStatus):string{return status==='authorized'?'#22c55e':status==='denied'?'#ef4444':status==='unavailable'?'#6b7280':'#f59e0b';}
