import { Platform } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import { WorkoutActivityType, WorkoutTypeIdentifier, isHealthDataAvailable, requestAuthorization, queryWorkoutSamples, queryStatisticsForQuantity, type WorkoutProxyTyped } from '@kingstinct/react-native-healthkit';
const HEALTHKIT_PERMISSIONS_KEY='@alchemize_healthkit_permissions'; const HEALTHKIT_LAST_SYNC_KEY='@alchemize_healthkit_last_sync';
const ACTIVE_ENERGY_IDENTIFIER='HKQuantityTypeIdentifierActiveEnergyBurned' as const; const EXERCISE_TIME_IDENTIFIER='HKQuantityTypeIdentifierAppleExerciseTime' as const; const STEP_COUNT_IDENTIFIER='HKQuantityTypeIdentifierStepCount' as const;
export type HealthKitPermissionStatus='notDetermined'|'authorized'|'denied'|'unavailable';
export interface HealthKitPermissions{activeEnergy:HealthKitPermissionStatus;workouts:HealthKitPermissionStatus;exerciseMinutes:HealthKitPermissionStatus;overallStatus:HealthKitPermissionStatus;lastUpdated:string|null;}
export interface HealthKitWorkout{id:string;workoutType:string;startDate:string;endDate:string;duration:number;caloriesBurned:number|null;source:'apple_health'|'manual'|'estimated';sourceName:string;isEstimated:boolean;}
export interface HealthKitActivityData{date:string;activeEnergyBurned:number;exerciseMinutes:number;steps:number;workouts:HealthKitWorkout[];}
const DEFAULT_PERMISSIONS:HealthKitPermissions={activeEnergy:'notDetermined',workouts:'notDetermined',exerciseMinutes:'notDetermined',overallStatus:'notDetermined',lastUpdated:null};
const LABELS:Partial<Record<keyof typeof WorkoutActivityType,string>>={traditionalStrengthTraining:'Strength Training',functionalStrengthTraining:'Functional Training',highIntensityIntervalTraining:'HIIT',crossTraining:'Cross Training',danceInspiredTraining:'Dance',mixedMetabolicCardioTraining:'Mixed Cardio'};
function formatActivity(type:WorkoutActivityType){const key=WorkoutActivityType[type] as keyof typeof WorkoutActivityType|undefined;if(!key)return'Workout';if(LABELS[key])return LABELS[key]!;const s=key.replace(/([a-z])([A-Z])/g,'$1 $2');return s.charAt(0).toUpperCase()+s.slice(1);}
function mapWorkout(w:WorkoutProxyTyped):HealthKitWorkout{return{id:w.uuid,workoutType:formatActivity(w.workoutActivityType),startDate:w.startDate.toISOString(),endDate:w.endDate.toISOString(),duration:Math.max(0,Math.round(w.duration.quantity)),caloriesBurned:w.totalEnergyBurned?Math.max(0,Math.round(w.totalEnergyBurned.quantity)):null,source:'apple_health',sourceName:w.sourceRevision?.source?.name??'Apple Health',isEstimated:false};}
function localDateKey(date:Date){return`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function isHealthKitAvailable(){return Platform.OS==='ios'&&isHealthDataAvailable();}
export function isHealthKitSupported(){if(Platform.OS==='web')return{supported:false,reason:'HealthKit is not available on web. Use the mobile app to sync wearable data.'};if(Platform.OS==='android')return{supported:false,reason:'Apple Health is only available on iOS devices.'};if(!isHealthDataAvailable())return{supported:false,reason:'Health data is not available on this device.'};return{supported:true,reason:'HealthKit is available on this device.'};}
export async function getStoredPermissions(){try{const s=await AsyncStorage.getItem(HEALTHKIT_PERMISSIONS_KEY);if(s)return JSON.parse(s) as HealthKitPermissions;}catch(e){console.error('[HealthKit] Error loading permissions:',e);}return DEFAULT_PERMISSIONS;}
export async function savePermissions(p:HealthKitPermissions){try{await AsyncStorage.setItem(HEALTHKIT_PERMISSIONS_KEY,JSON.stringify(p));}catch(e){console.error('[HealthKit] Error saving permissions:',e);}}
export async function requestHealthKitPermissions(){const{supported}=isHealthKitSupported();if(!supported){const p={...DEFAULT_PERMISSIONS,activeEnergy:'unavailable',workouts:'unavailable',exerciseMinutes:'unavailable',overallStatus:'unavailable',lastUpdated:new Date().toISOString()} as HealthKitPermissions;await savePermissions(p);return p;}const ok=await requestAuthorization({toRead:[ACTIVE_ENERGY_IDENTIFIER,EXERCISE_TIME_IDENTIFIER,STEP_COUNT_IDENTIFIER,WorkoutTypeIdentifier]});const status:HealthKitPermissionStatus=ok?'authorized':'denied';const p:HealthKitPermissions={activeEnergy:status,workouts:status,exerciseMinutes:status,overallStatus:status,lastUpdated:new Date().toISOString()};await savePermissions(p);return p;}
export async function checkHealthKitPermissions(){const p=await getStoredPermissions();if(p.overallStatus==='notDetermined')return p;if(!isHealthKitSupported().supported&&p.overallStatus==='authorized')return{...p,overallStatus:'unavailable' as const,activeEnergy:'unavailable' as const,workouts:'unavailable' as const,exerciseMinutes:'unavailable' as const};return p;}
export async function revokeHealthKitPermissions(){await savePermissions(DEFAULT_PERMISSIONS);await AsyncStorage.removeItem(HEALTHKIT_LAST_SYNC_KEY);}
export async function getLastSyncTime(){try{return await AsyncStorage.getItem(HEALTHKIT_LAST_SYNC_KEY);}catch{return null;}}
export async function setLastSyncTime(time:string){try{await AsyncStorage.setItem(HEALTHKIT_LAST_SYNC_KEY,time);}catch(e){console.error('[HealthKit] Error saving last sync time:',e);}}
export async function fetchHealthKitWorkouts(startDate:Date,endDate:Date):Promise<HealthKitWorkout[]>{if((await checkHealthKitPermissions()).workouts!=='authorized')return[];try{return(await queryWorkoutSamples({filter:{date:{startDate,endDate}},limit:0,ascending:false})).map(mapWorkout);}catch(e){console.error('[HealthKit] Error fetching workouts:',e);return[];}}
export async function fetchHealthKitActivity(date:Date):Promise<HealthKitActivityData|null>{if((await checkHealthKitPermissions()).overallStatus!=='authorized')return null;const start=new Date(date);start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);try{const[energy,exercise,steps,workouts]=await Promise.all([queryStatisticsForQuantity(ACTIVE_ENERGY_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:start,endDate:end}}}),queryStatisticsForQuantity(EXERCISE_TIME_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:start,endDate:end}}}),queryStatisticsForQuantity(STEP_COUNT_IDENTIFIER,['cumulativeSum'],{filter:{date:{startDate:start,endDate:end}}}),fetchHealthKitWorkouts(start,end)]);return{date:localDateKey(start),activeEnergyBurned:Math.max(0,Math.round(energy.sumQuantity?.quantity??0)),exerciseMinutes:Math.max(0,Math.round(exercise.sumQuantity?.quantity??0)),steps:Math.max(0,Math.round(steps.sumQuantity?.quantity??0)),workouts};}catch(e){console.error('[HealthKit] Error fetching activity:',e);return null;}}
export async function syncHealthKitData():Promise<{success:boolean;workoutsImported:number;message:string}>{if((await checkHealthKitPermissions()).overallStatus!=='authorized')return{success:false,workoutsImported:0,message:'HealthKit permissions not granted. Please enable in settings.'};const end=new Date();const start=new Date();start.setDate(start.getDate()-7);start.setHours(0,0,0,0);const workouts=await fetchHealthKitWorkouts(start,end);const{workoutSessionsDb,normalizedMetricsDb}=await import('./database');let imported=0;for(const w of workouts){const id=`healthkit_${w.id}`;if(await workoutSessionsDb.getById(id))continue;await workoutSessionsDb.create({id,templateId:'healthkit',startedAt:new Date(w.startDate).getTime(),endedAt:new Date(w.endDate).getTime(),durationMinutes:w.duration,completed:true,caloriesEstimate:w.caloriesBurned??null,source:'wearable'});imported++;}for(let cursor=new Date(start);cursor<=end;cursor.setDate(cursor.getDate()+1)){const a=await fetchHealthKitActivity(new Date(cursor));if(!a)continue;const metric={id:`healthkit_${a.date}`,date:a.date,activeMinutes:a.exerciseMinutes,caloriesActive:a.activeEnergyBurned,steps:a.steps,source:'wearable' as const,deviceType:'none' as const};const existing=await normalizedMetricsDb.getByDate(a.date);if(existing)await normalizedMetricsDb.update({...existing,...metric,id:existing.id});else await normalizedMetricsDb.create(metric);}await setLastSyncTime(new Date().toISOString());return{success:true,workoutsImported:imported,message:imported>0?`Synced ${imported} new workout${imported===1?'':'s'} from Apple Health`:workouts.length>0?'Already up to date — activity refreshed from Apple Health':'No workouts found — daily Apple Health activity was still refreshed'};}
export function formatWorkoutType(type:string){const m:Record<string,string>={'HKWorkoutActivityTypeRunning':'Running','HKWorkoutActivityTypeWalking':'Walking','HKWorkoutActivityTypeCycling':'Cycling','HKWorkoutActivityTypeSwimming':'Swimming','HKWorkoutActivityTypeYoga':'Yoga','HKWorkoutActivityTypeStrengthTraining':'Strength Training','HKWorkoutActivityTypeHighIntensityIntervalTraining':'HIIT','HKWorkoutActivityTypeFunctionalStrengthTraining':'Functional Training','HKWorkoutActivityTypeCoreTraining':'Core Training','HKWorkoutActivityTypeElliptical':'Elliptical','HKWorkoutActivityTypeRowing':'Rowing','HKWorkoutActivityTypeDance':'Dance','HKWorkoutActivityTypePilates':'Pilates'};return m[type]||type;}
export function getPermissionStatusLabel(s:HealthKitPermissionStatus){return s==='authorized'?'Enabled':s==='denied'?'Denied':s==='unavailable'?'Unavailable':'Not Set';}
export function getPermissionStatusColor(s:HealthKitPermissionStatus){return s==='authorized'?'#22c55e':s==='denied'?'#ef4444':s==='unavailable'?'#6b7280':'#f59e0b';}
